---
- hosts: logstash
  user: $user
  sudo: yes
  sudo_user: root

  vars_files:
    - vars/logstash.yml

  tasks:
    - include: tasks/setup.yml

  handlers:
    - include: handlers/logstash-indexer.yml
    - include: handlers/logstash-shipper.yml
