---
# Install Logstash indexer config
- name: "Install Logstash indexer config"
  action: template src=logstash_indexer.conf.j2 dest={{ logstash.indexer.conf }} owner=root group=root mode=0755
  when: with_indexer
  notify:
    - "Restart Logstash"

# Install Logstash shipper config
- name: "Install Logstash shipper config"
  action: template src=logstash_shipper.conf.j2 dest={{ logstash.shipper.conf }} owner=root group=root mode=0755
  when: with_shipper
  register: shipper_config
  notify:
    - "Restart Logstash"

# Set /etc/defaults/logstash to start on boot
- name: "Change defaults to start logstash on boot"
  lineinfile: dest=/etc/default/logstash regexp="START=no" line="START=yes" state=present mode=0755 owner=root group=root

# Start Logstash 
- name: "Start Logstash"
  action: service name=logstash state=started
  when: with_indexer or with_shipper