---
# Include Debian Elasticsearch logstash repo
- include: debian-repo.yml tags=logstash
  sudo: yes
  when: ansible_distribution in [ 'Debian', 'Ubuntu']

# Install Logstash
- include: logstash.yml tags=logstash
  sudo: yes
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]